attempt to readd log check in test action workflow

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -16,8 +16,8 @@ jobs:
         run: |
           echo ::set-output name=build_tag::test
           echo ::set-output name=container_name::docker-socat
-          echo ::set-output name=running_timeout::120
-          echo ::set-output name=running_log_check::starting data transfer loop with FDs
+          echo ::set-output name=running_timeout::60
+          echo ::set-output name=running_log_check::I am running on
       -
         # https://github.com/actions/checkout
         name: Checkout
@@ -40,20 +40,20 @@ jobs:
       -
         name: Test run
         run: |
-          # TIMEOUT=$((SECONDS + ${{ steps.prepare.outputs.running_timeout }}))
-          # while read LOGLINE; do
-          #   echo ${LOGLINE}
-          #   if [[ ${LOGLINE} == *"${{ steps.prepare.outputs.running_log_check }}"* ]]; then
-          #     echo "Container up!"
-          #     break
-          #   fi
-          #   if [[ $SECONDS -gt ${TIMEOUT} ]]; then
-          #     >&2 echo "ERROR: Failed to run ${{ steps.prepare.outputs.container_name }} container"
-          #     docker rm -f ${{ steps.prepare.outputs.container_name }} > /dev/null 2>&1 || true
-          #     exit 1
-          #   fi
-          # done < <(docker logs -f ${{ steps.prepare.outputs.container_name }} 2>&1)
-          < <(docker logs -f ${{ steps.prepare.outputs.container_name }} 2>&1)
+          TIMEOUT=$((SECONDS + ${{ steps.prepare.outputs.running_timeout }}))
+          while read LOGLINE; do
+            echo ${LOGLINE}
+            if [[ ${LOGLINE} == *"${{ steps.prepare.outputs.running_log_check }}"* ]]; then
+              echo "Container up!"
+              break
+            fi
+            if [[ $SECONDS -gt ${TIMEOUT} ]]; then
+              >&2 echo "ERROR: Failed to run ${{ steps.prepare.outputs.container_name }} container"
+              docker rm -f ${{ steps.prepare.outputs.container_name }} > /dev/null 2>&1 || true
+              exit 1
+            fi
+          done < <(docker logs -f ${{ steps.prepare.outputs.container_name }} 2>&1)
+          
           CONTAINER_STATUS=$(docker container inspect --format "{{.State.Status}}" ${{ steps.prepare.outputs.container_name }})
           if [[ ${CONTAINER_STATUS} != "running" ]]; then
             >&2 echo "ERROR: Container ${{ steps.prepare.outputs.container_name }} returned status '$CONTAINER_STATUS'"
